# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='shown',
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
